[book]
authors = ["JonathanxD", "KoresFramework"]
language = "en"
multilingual = false
src = "book/src"
title = "Meili-ktr Book"

[build]
build-dir = "docs"

[output.html]
mathjax-support = true
default-theme = "navy"
edit-url-template = "https://github.com/koresframework/meili-ktr/edit/main/book/{path}"
